# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run config script
      run: |
        ./configure.sh
    - name: Test with unittest
      run: |
        cd tests/unit_tests/
        ./run_tests.sh
